#!/bin/sh

mkdir res 2>/dev/null

# Перетворити JSON-файл на звичайний текст
if [ $1 == 'json' ]; then
	shift #json
	for arg in "$@"
	do
		text=$(cat $arg)
		
                text=$(echo "$text" | sed -E "s/^.*: \"//g")
                text=$(echo "$text" | sed -E "s/^  \{//g")
                text=$(echo "$text" | sed -E "s/^  },//g")
                text=$(echo "$text" | sed -E "s/^  }//g")
                text=$(echo "$text" | sed -E "s/^\[//g")
                text=$(echo "$text" | sed -E "s/^]//g")
                text=$(echo "$text" | sed -E "s/\"$//g")

		text=$(echo "$text" | sed -E -z 's/\n+/\n/g')

		echo "$text" > res/$arg.text.txt
	done
	exit 0
fi

#Загальні регулярні вирази заміни тексту для всіх творів
#На https://regexr.com/ можна зручно їх проєктувати/перевіряти
patterns=(	
                ', -/, —'
                ' - / — '
		'(^\.\.)\. -/, —'
		'^ -/—'
                '^ —/—'
                '^" /— '
                '^“/— '
		'“/— '
		'”/'
                '^"/— '
                '^-/—'
                ': - /, — '
                ': -/, — '
		': —(\w)/, — \1'
		': —/, — '
		': "/, — '
		': «/, — '
                ' "/ «'
		'\." /, — '
                '"/»'
                ' — $/'
                '‘/«'
                '[^a-zA-Zа-яА-я]’/»'
		'» —/, —'
		'\. «/. — '
		' «\./.'
		'«\./.'
		'»$/'
		'—  /— '
		'»\./.'
		'\?,/?'
		'\?\./?'
		'\?»/?'
		'!,/!'
		'!»/!'
		'\.,/,'
		'»,/,'
#		'\.»/.'
                '…/...'
		'и і /и й ' # допомагати і підтримувати -> допомагати й підтримувати
		'і і /і й '
		' в (.в)/ у \1'
                '(Розділ [0-9]+.*):/\1.'
                '(Розділ.*)/\n\1\n'
)

# Не використовувати загальні регулярні вирази
if [ $1 == '-c' ]; then
	shift
	patterns=()
fi


multi_line_patterns=(	
		'\n+/\n'
	)

# Додаткові правила заміни окремого твору
# На кожному рядку регулярний вираз
cin_path=''

if [ -f 'cin.txt' ]; then
	cin_path='./cin.txt'
elif [ -f '../cin.txt' ]; then
	cin_path='../cin.txt'
fi

if [ -n "$cin_path" ]; then
	while IFS="" read -r exp
	do
		if [ -z "$exp" ]; then
			continue
		fi

		patterns+=("$exp")
	done < $cin_path
fi

# Заміна тексту у файлах використовуючи регулярні вирази
for arg in "$@"
do
	text=$(cat $arg)
	
	for exp in "${multi_line_patterns[@]}"; do
                text=$(echo "$text" | sed -E -z "s/$exp/g")
        done

        for exp in "${patterns[@]}"; do
                text=$(echo "$text" | sed -E "s/$exp/g")
        done

        echo "$text" > res/$arg
done

