#!/bin/sh

if [ $# -eq 0 ]; then
        for arg in $(ls | sort -V)
        do
                cat $arg >> all.txt
        done

else
        for arg in "$@"
        do
                cat $arg >> all.txt
        done

fi
