#!/bin/sh

ext="tr.txt"

for arg in "$@"
do
	if [[ $arg == *.$ext ]]; then continue; fi

	trans -b -no-warn -t uk -show-alternatives n -show-dictionary n -show-prompt-message n -i $arg -o "$arg.$ext"
	echo "done $arg"
	sleep 1
done
wait
echo "finish"
