#!/bin/sh

for arg in "$@"
do
	lines=$(cat $arg | wc -l -)
	del=2 #перші 2 рядки пропускаємо - це назва розділу та новий рядок
	lines="$(($lines-$del))"
	text=$(tail -n $lines $arg)
	(echo "$text" | grep '^[[:space:]]*$' -q -) && echo $arg >> fix_list.txt && echo "find $arg"
done

